### ISSUE TITLE
Why are there no documentation about the post body?

### ISSUE THREAD

**Issue by phper-chen** [rakyll/hey#145]
I can`t send anything in POST method

**Comment by leucos** [comment]
@phper-chen  works for me:

```
hey -m POST -n 10 -c 10 -H 'Content-Type: application/json' -d '{ "name": "foo", "phone": "1234"}' http://localhost:8000/api/v1/whatever/
```

**Comment by phper-chen** [comment]
> @phper-chen works for me:
> 
> ```
> hey -m POST -n 10 -c 10 -H 'Content-Type: application/json' -d '{ "name": "foo", "phone": "1234"}' http://localhost:8000/api/v1/whatever/
> ```

It seems to be the arguments of the command must be keep a certain order

**Comment by ewilde** [comment]
@phper-chen yes is appears the `-d` must come before the URL

works:

hey -m POST -n 10 -c 10 -H 'Content-Type: application/json' -d '{ "name": "foo", "phone": "1234"}' http://localhost:8000/api/v1/whatever/


does not work:

hey -m POST -n 10 -c 10 -H 'Content-Type: application/json' http://localhost:8000/api/v1/whatever/ -d '{ "name": "foo", "phone": "1234"}'

**Comment by phper-chen** [comment]
> @phper-chen yes is appears the `-d` must come before the URL
> 
> works:
> 
> hey -m POST -n 10 -c 10 -H 'Content-Type: application/json' -d '{ "name": "foo", "phone": "1234"}' http://localhost:8000/api/v1/whatever/
> 
> does not work:
> 
> hey -m POST -n 10 -c 10 -H 'Content-Type: application/json' http://localhost:8000/api/v1/whatever/ -d '{ "name": "foo", "phone": "1234"}'

Thanks for ur reply~
