### ISSUE TITLE
can't download hey

### ISSUE THREAD

**Issue by MyOldSkyGrandfather** [rakyll/hey#161]
like this, no any response,can u help me thnx
![image](https://user-images.githubusercontent.com/22900812/59338515-0cdb6a00-8d35-11e9-8a83-b19e9b6150ff.png)

**Comment by MyOldSkyGrandfather** [comment]
@rakyll @cyx @broady @rubenk @pasc

**Comment by broady** [comment]
If there was no output, the command installed correctly to `$(go env GOPATH)/bin`
