### ISSUE TITLE
Release links are broken

### ISSUE THREAD

**Issue by marcosnils** [rakyll/hey#168]
Getting some gcloud 403's when trying to download binaries.

**Comment by sinthuja** [comment]
When trying to download the binary getting below error. 
<img width="707" alt="Screen Shot 2019-08-05 at 4 38 40 PM" src="https://user-images.githubusercontent.com/7677649/62460409-8d4fa180-b79f-11e9-946c-87e0b5055812.png">

**Comment by lrstanley** [comment]
Ran into this too, looks like the readme was updated but not the releases page for the previous release:

https://github.com/rakyll/hey/commit/1a1cc26b653533736d6cf8b5574af23c1a26addd#diff-04c6e90faac2675aa89e2176d2eec7d8L61

**Comment by alexellis** [comment]
```
<Error>
<Code>UserProjectAccountProblem</Code>
<Message>User project billing account not in good standing.</Message>
<Details>
The billing account for project 938381945713 is disabled in state absent
</Details>
</Error>
```

I'm getting the same. @rakyll please could you have a look when you have time?

**Comment by alexellis** [comment]
Thanks. Could the release links be updated by any chance too? Is this issue still valid?

**Comment by rakyll** [comment]
This is resolved a while ago, closing it now.

**Comment by marcosnils** [comment]
:pray: thx!.
