### ISSUE TITLE
Get https://www.example.com/: remote error: tls: internal error

### ISSUE THREAD

**Issue by berti34** [rakyll/hey#194]
Hi,

running a request to a website with port number and the webserver then replies HTTP 301 to a https adress results in an TLS error:

```
hey_linux_amd64 -m GET -n 1 -c 1 'http://www.bild.de:80/'
...
  [1]   Get https://www.bild.de/: remote error: tls: internal error

```

**Comment by JohnStarich** [comment]
This is happening for me as well, even on `https://...:443`. Removing the port number from my URL as a work-around fixed the error.

**Comment by moraesjeremias** [comment]
> This is happening for me as well, even on `https://...:443`. Removing the port number from my URL as a work-around fixed the error.

It worked, TYSM @JohnStarich!
