### ISSUE TITLE
 first path segment in URL cannot contain colon

### ISSUE THREAD

**Issue by fjfzeagle** [rakyll/hey#205]
-x  HTTP Proxy address as host:port

hey.exe -n 1 -c 1 -x 127.0.0.0:8888  http://www.test.com:8060/hello
error:
parse 127.0.0.0:8888: first path segment in URL cannot contain colon

**Comment by ringerl** [comment]
Is there some workaround?

**Comment by liuzhenyilang** [comment]
you can try below:
hey.exe -n 1 -c 1 -x http://www.test.com:8060/hello

**Comment by marcwickenden** [comment]
I think this is just a README issue. I've raised a [PR](https://github.com/rakyll/hey/pull/240) but the value of `-x` should be a URL which can be parsed by net/url Parse:

https://github.com/rakyll/hey/blob/33a965eeeb7b0351b50c8e1d8de7ae50bff3d2be/hey.go#L186

i.e. `http://127.0.0.1:8888`.

**Comment by fjfzeagle** [comment]
Works fine,thank you!
