### ISSUE TITLE
does it still work in windows?

### ISSUE THREAD

**Issue by prabhakarreddy1234** [rakyll/hey#236]
I can't get it to work in windows. It would be helpful if some instructions are provided.

**Comment by prabhakarreddy1234** [comment]
Thanks. it worked.

**Comment by jvasquezv** [comment]
I can't get it to work in windows. 

![image](https://user-images.githubusercontent.com/4551379/170884131-f7a3f558-267f-45df-ba1c-12c14403420e.png)
