### ISSUE TITLE
go get -u github.com/rakyll/hey

### ISSUE THREAD

**Issue by goodforever** [rakyll/hey#26]
go get -u github.com/rakyll/hey
package golang.org/x/net/http2: directory "/Users/user/gowork/src/golang.org/x/net/http2" is not using a known version control system
package net/http/httptrace: unrecognized import path "net/http/httptrace" (import path does not begin with hostname)

**Comment by ericmdantas** [comment]
`hey` only works with Golang 1.7 and above.
