### ISSUE TITLE
httptrace stats

### ISSUE THREAD

**Issue by rakyll** [rakyll/hey#3]
With the addition of the new httptrace package, https://golang.org/pkg/net/http/httptrace/, there is more possibility to show more precise information all along the different events during a request.

Introduce an optional experimental flag to use httptrace and display the data.

**Comment by JRonak** [comment]
@rakyll  
Added -http-trace and have opened a pull request.
Currently supports average Connection setup, Dns lookup, request and response read and write times.
Please suggest

**Comment by rakyll** [comment]
Closed experimentally by https://github.com/rakyll/hey/pull/4.
