### ISSUE TITLE
Outputting in CSV format blocks on channel forever

### ISSUE THREAD

**Issue by crhino** [rakyll/hey#32]
Running hey with `-o csv` flag enabled causes the binary to hang forever.

This is caused by the return statement [here](https://github.com/rakyll/hey/blob/master/requester/requester.go#L92-L94), which returns without synchronizing with the unbuffered [stopCh channel](https://github.com/rakyll/hey/blob/master/requester/requester.go#L124). The binary then attempts to send a message on the stopCh and blocks forever.

**Comment by Nino-K** [comment]
Created a PR which fixes this issue [here](https://github.com/rakyll/hey/pull/33).

**Comment by rakyll** [comment]
Fixed via 2969c6acaf72a6b91cd113e8c0b9a6b9be4a9942.
