### ISSUE TITLE
Request Body is Always Empty?

### ISSUE THREAD

**Issue by mtowers** [rakyll/hey#36]
I'm attempting to POST a message body to a Sinatra app running under Puma but the body is always reported in Sinatra as malformed/empty.  Making the same request via `curl` works as expected.  I've also tried with GET as my verb with the same result.

ex. ```hey -c 1 -n 1 -m POST -d "some text" http://localhost:4567/post-test```

I get the same result when I try to pass a file as the body with `-D`

ex. ```hey -c 1 -n 1 -m POST -D "test.json" http://localhost:4567/post-test```

My Sinatra app ~=
```
class App < Sinatra::Base

  post 'post-test' do
    puts request.body.read
  end

end
```

Sinatra logs the following:
```
2016-11-14 16:30:14 -0800: HTTP parse error, malformed request (): #<Puma::HttpParserError: Invalid HTTP format, parsing fails.>
2016-11-14 16:30:14 -0800: ENV: {"rack.version"=>[1, 3], "rack.errors"=>#<IO:<STDERR>>, "rack.multithread"=>true, "rack.multiprocess"=>false, "rack.run_once"=>false, "SCRIPT_NAME"=>"", "QUERY_STRING"=>"", "SERVER_PROTOCOL"=>"HTTP/1.1", "SERVER_SOFTWARE"=>"puma 3.5.2 Amateur Raccoon Rocketry", "GATEWAY_INTERFACE"=>"CGI/1.2"}
---
```

Am I missing something obvious?

**Comment by ptere** [comment]
I’m seeing extraneous characters inserted into the request body. E.g. if I run this against a simple server that logs requests

    $ hey -n 1 -c 1 -m POST -d 'hey world' http://127.0.0.1:50000

I see this come in:

```
POST / HTTP/1.1
Host: 127.0.0.1:50000
User-Agent: Go-http-client/1.1
Transfer-Encoding: chunked
Content-Type: text/html
Accept-Encoding: gzip

1
h
8
ey world
0


```

**Comment by 512444693** [comment]
How to close "Transfer-Encoding: chunked"?

**Comment by JasonZhangHkust** [comment]
Hello there,
I meet the same problem, the post request body is empty. Has it been fixed ?

**Comment by ptman** [comment]
For me -d worked as specified, but no ruby on the server side

**Comment by mathewcohle** [comment]
The same problem:

```
hey -m POST -T "application/json" -H "Authorization: Key XXX" -d '{"x": 0, "y": 1}' server-url
```

But the server receives following header and body:
```
Header: 
'Authorization': 'Key XXX'
'Transfer-Encoding': 'chunked'
'User-Agent': 'Go-http-client/1.1'
'Host': 'server-url'
'Content-Type': 'application/json'
'Accept-Encoding': 'gzip'
```

```
Body: 
'' (empty string)
```

Why is the body not sent to the server? Also working with curl.
