### ISSUE TITLE
Provide binary releases

### ISSUE THREAD

**Issue by ahmetb** [rakyll/hey#37]
I feel like I should not be have to install Go on my machine just to use `hey`.

This project can provide cross-compiled binary releases built via Travis CI easily. I can help out with the setup but it will require someone with write privileges on the repo to configure Travis.

**Comment by jorinvo** [comment]
https://github.com/goreleaser/releaser might also be a simple solution.

**Comment by ahmetb** [comment]
According to the 👍 s, like there is some interest. However this requires project owner to go set up release process with Travis. Is there anything I can help with?

**Comment by ericmdantas** [comment]
Maybe set up a PR with the changes to the `.travis.yml`?

**Comment by ahmetb** [comment]
@ericmdantas still requires admin access on the repo to create an encrypted Github API key. example: https://github.com/ahmetb/govvv/blob/11577df3c95b9df53a1ef2f971e2beb6717de443/.travis.yml#L23-L26

**Comment by ericmdantas** [comment]
Oh, I see.

Let's just wait then :smile:

**Comment by mdakin** [comment]
@ahmetb Maybe I can help, what needs to be done?

**Comment by ahmetb** [comment]
It would be good to have linux/darwin/windows binaries automatically attached to each tag/release.

See: https://github.com/ahmetb/govvv/releases
Code: https://github.com/ahmetb/govvv/blob/11577df3c95b9df53a1ef2f971e2beb6717de443/.travis.yml#L23-L26

You probably need to set up Travis CI and create a "deploy" step with the key travis CLI gives you.

**Comment by ahmetb** [comment]
Pinging this.

Please use https://github.com/goreleaser/goreleaser or something.

**Comment by mdakin** [comment]
@ahmetb 
Sorry, I was temporarily maintaining Hey, I don't have time now, maybe @rakyll or someone else could help.

**Comment by sergeevabc** [comment]
Could you be so kind to generate ```.exe``` for the rest of us who are mere Windows users w/o compiler?

**Comment by alexellis** [comment]
@ahmetb I'd be really keen to have binary releases too. @stefanprodan and I often recommend people to use `hey` in our tutorials and workshops with GKE/Kubernetes and this would remove the need for them to install Golang on their host machines (which is often distracting). 

Is there a way to get this moved forward? I have plenty of examples of doing this in openfaas/faas-cli / alexellis/inlets and others.

**Comment by ahmetb** [comment]
@rakyll Out of curiosity, are there any active maintainers of the project who might be willing to take time to set this up? I'm personally willing to set up a goreleaser+.travis.yml installation.

**Comment by alexellis** [comment]
I was thinking that an interim solution would be to fork, buy a domain and set up binary releases with a HTTPS / short-url. If the maintainers are willing to take it over we could change the ownership and remove the fork.

@ahmetb ?

Binaries for ARMHF / ARM64 / x86_64 would be ideal and an install.sh

```
curl -sLS https://hey.sh | bash
```

**Comment by alexellis** [comment]
The fork would only exist as a soft fork for syncing with origin/master and for CI.

**Comment by ahmetb** [comment]
I'm not sure why buying a domain name and making people do curl|sh is a good idea, where we can just provide binary releases on the Releases tab that people can easily download with curl/wget.

**Comment by alexellis** [comment]
That part is obviously optional, but I feel that having a memorable cli command to get hey would be a win.

**Comment by rakyll** [comment]
0.1.2 is released with binary downloads. See the release notes at https://github.com/rakyll/hey/releases/tag/v0.1.2.

**Comment by sergeevabc** [comment]
@rakyll, being a Windows user, I downloaded https://storage.googleapis.com/jblabs/dist/hey_darwin_v0.1.2, gave it `.exe` extension, launched… it’s obviously a wrong binary for Windows.

**Comment by rakyll** [comment]
Sorry, fixed the link.

**Comment by alexellis** [comment]
:+1: 

Please could you add binaries for armhf/arm64 for this release of the next?

Could I ask if you plan on doing binary releases going forward?

Thanks,

Alex
