### ISSUE TITLE
Run load for a duration

### ISSUE THREAD

**Issue by bharatkrishna** [rakyll/hey#39]
Ability to run load for a duration would helpful. For example, I'd like to run load for 10 mins to see how my server performs on sustained load.

**Comment by lafolle** [comment]
You can accomplish this by using `-n` and `-q` flags,  as of now.  Say you want to generate load for 10m at 50r/s (q),  set `n` to 50*600.

This might not be accurate,  as maintaining q can be difficult if requests abruptly take large time.

**Comment by mdakin** [comment]
I will add this feature after pr #74  is in.

**Comment by mdakin** [comment]
@bharatkrishna I created #74 , feel free to review it.
