### ISSUE TITLE
Hey fails to print report if requests time out

### ISSUE THREAD

**Issue by fdavis** [rakyll/hey#55]
I was running some tests on live servers that didn't print results due to some requests timing out and so I created the following test:

I'm running a docker container with nginx/uwsgi/flask/python and the sleep path is:

```
@app.route('/sleep', methods=('GET',))
def shleep():
    time.sleep(5000)
    return 'lolcats'
```

```
{15:23}~/git/ ✓ ➭ ~/go/bin/hey -c 700 -n 10000 http://localhost/sleep
Error distribution:
  [2376]	Get http://localhost/sleep: EOF
  [4]	Get http://localhost/sleep: http: server closed idle connection
  [7420]	Get http://localhost/sleep: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

**Comment by mdakin** [comment]
Hey only print latency percentiles & histogram etc only for responses with no errors. Otherwise only prints error distribution.
