### ISSUE TITLE
Token authentication fails

### ISSUE THREAD

**Issue by jeroenes** [rakyll/hey#6]
Thanks for <hey>! Really allowed me to stresstest my server in a much better way! 

Unlike  <curl> though, <hey>  does not allow token authentication. If I only supply a username w/o colon, I get back a message like 'cannot parse input'.

The workaround of course is to push it through <base64> and than feed it as a Basic auth header.

**Comment by rakyll** [comment]
You can use the -H flag to set a custom Authorization header.

```
hey -H "Authorization: <token>" ...
```
