### ISSUE TITLE
Http trace improvements

### ISSUE THREAD

**Issue by JRonak** [rakyll/hey#7]
Provide detailed trace report such as Fastest dns, slowest dns and other trace fields
Histogram for trace fields
Add  trace fields to CSV

**Comment by rakyll** [comment]
> Detailed trace report such as Fastest dns, slowest ...
> Histogram for trace fields
> Add trace fields to csv

These sound nice.

> Progress bar or counter

Not an interactive bar but an update line would be nice to have.

Is it possible to open issues for the other suggestions? It is hard to track/discuss everything under a single issue.
