### ISSUE TITLE
net/http/httptrace import path does not begin with hostname)

### ISSUE THREAD

**Issue by integrii** [rakyll/hey#9]
package net/http/httptrace: unrecognized import path "net/http/httptrace" (import path does not begin with hostname)

go 1.6 on centos with RPM version installed

**Comment by integrii** [comment]
this does not happen on OS X with Go 1.71

**Comment by integrii** [comment]
looks like httptrace was added just this year. im guessing its not in 1.6.  might want to ptu a warning on the readme. https://github.com/golang/go/commits/master/src/net/http/httptrace

**Comment by ericmdantas** [comment]
Yup, that'll only work with Go 1.7 and beyond.

Dup of https://github.com/rakyll/hey/issues/5.
